### ISSUE TITLE
Unintended dependancy

### ISSUE THREAD

**Issue by hell2o** [mannly01/TransferAll#18]
It seems that this mod requires [QoLmod](https://www.nexusmods.com/carmechanicsimulator2021/mods/105?) to function, this is not stated on the mod page or the readme as far as I can tell. 
An error is thrown when trying to move items in the warehouse without it, log file attached
[MelonLoader_24-03-26_14-24-30.559.log](https://github.com/mannly01/TransferAll/files/14760037/MelonLoader_24-03-26_14-24-30.559.log).

Installing QoLmod resolved this error.

**Comment by mannly01** [comment]
QoLmod is not supposed to be a dependency. This mod only makes a change if it is present. This behavior is a bug.
