### ISSUE TITLE
Transfer all doesn't work in warehouse

### ISSUE THREAD

**Issue by bacempro** [mannly01/TransferAll#21]
I see that the mod is loading, it's detecting The QoL mod but pressing K doesn't do anything :/ (I even tried using v 1.3.1 and still nothing)

Tried it in Barn and Junkyard, it actually works, but it doesn't when in garage (doesn't show the tooltip and doesn't do anything when I have warehouse open)

**Comment by mannly01** [comment]
Please download version 1.4.1 and then send me the TransferAll.log that is created in the Mods folder. This way I can troubleshoot your problem. Thanks!

**Comment by GermanioBR** [comment]
This is my log, but I think that doesn't show enough:

Transfer All - 1.4.1
CMS 2021 - 1.0.34
Log Created: 04-26-2024 20:38:05
20:38:08	OnLateInitializeMelon	QoLmod Found, showPopupforGroupAddedInventory: True.
20:38:08	OnLateInitializeMelon	QoLmod Found, showPopupforAllPartsinGroup: True.
20:53:09	OnSceneWasUnloaded	Leaving Junkyard.
21:08:51	OnDeinitializeMelon	QoLmod Found, showPopupforGroupAddedInventory: True.
21:08:51	OnDeinitializeMelon	QoLmod Found, showPopupforAllPartsinGroup: True.


I've tryied several times press 'K' and 'k' and even chance the key but no success until now.

**Comment by mannly01** [comment]
[TransferAll.zip](https://github.com/mannly01/TransferAll/files/15139542/TransferAll.zip)
Please use this file and then send me the new log created. There should be a lot more detail for troubleshooting.

**Comment by GermanioBR** [comment]
Hey George,

In attachment is my log file.
To be honest, it seems that the log can't call when the K key is pushed to
transfer in the warehouse.
I hope that even so this can help you.
You know, for someone like me that buys 16 pages of junk on every junkyard
visit, manually transfer every part is a pain...

Thanks again and let me know if you need any help.

GermanioBR

Em sáb., 27 de abr. de 2024 às 16:06, George Mann ***@***.***>
escreveu:

**Comment by mannly01** [comment]
The log got removed from your email. Please try and upload it directly to [Github](https://github.com/mannly01/TransferAll/issues/21).

Also, are you using a keyboard layout other than [US 104 QWERTY](https://en.wikipedia.org/wiki/QWERTY)?

**Comment by GermanioBR** [comment]
> The log got removed from your email. Please try and upload it directly to [Github](https://github.com/mannly01/TransferAll/issues/21).
> 
> Also, are you using a keyboard layout other than [US 104 QWERTY](https://en.wikipedia.org/wiki/QWERTY)?

I'm using a US QWERTY but with Brazilian Portuguese language... even so, I think the standard keys are the same.
It's a Dell G3 with a US QWERTY 101 keys keyboard... 



This the log file content:

Transfer All - 1.4.2
CMS 2021 - 1.0.34
Log Created: 04-28-2024 16:52:11
16:52:11	ConfigFile.Init	Called.
16:52:11	ConfigFile.Init	TransferAllItemsAndGroups: K.
16:52:11	ConfigFile.Init	TransferEntireJunkyardOrBarn: L.
16:52:11	ConfigFile.Init	SetPartConditionLower: Minus.
16:52:11	ConfigFile.Init	SetPartConditionHigher: Equals.
16:52:11	ConfigFile.Init	MinPartCondition: 90.
16:52:11	ConfigFile.Init	MinNumOfItemsWarning: 700.
16:52:11	ConfigFile.Init	TransferByCategory: True.
16:52:11	ConfigFile.Init	TransferPartsOnlyAtBarnOrJunkyard: False.
16:52:11	ConfigFile.Init	TransferMapsOrCasesOnlyAtBarnOrJunkyard: False.
16:52:14	OnLateInitializeMelon	Called.
16:52:14	OnLateInitializeMelon	QoLmod Found, showPopupforGroupAddedInventory: True.
16:52:14	OnLateInitializeMelon	QoLmod Found, showPopupforAllPartsinGroup: True.
16:56:14	OnSceneWasInitialized	SceneName: garage.
16:57:28	OnSceneWasInitialized	SceneName: Junkyard.
17:11:13	OnSceneWasUnloaded	Leaving Junkyard.
17:11:13	OnSceneWasUnloaded	SceneName: Junkyard.
17:11:37	OnSceneWasInitialized	SceneName: garage.
17:13:26	OnSceneWasInitialized	SceneName: Junkyard.
17:25:50	OnSceneWasUnloaded	Leaving Junkyard.
17:25:50	OnSceneWasUnloaded	SceneName: Junkyard.
17:26:12	OnSceneWasInitialized	SceneName: garage.
17:27:18	OnSceneWasInitialized	SceneName: Junkyard.
17:29:28	OnSceneWasUnloaded	Leaving Junkyard.
17:29:28	OnSceneWasUnloaded	SceneName: Junkyard.
17:29:51	OnSceneWasInitialized	SceneName: garage.
17:34:53	OnSceneWasInitialized	SceneName: Junkyard.
17:43:35	OnSceneWasUnloaded	Leaving Junkyard.
17:43:35	OnSceneWasUnloaded	SceneName: Junkyard.
17:43:57	OnSceneWasInitialized	SceneName: garage.
17:47:41	OnUpdate	Debug Key (J) Pressed.
17:48:50	OnUpdate	Debug Key (J) Pressed.
17:48:56	OnUpdate	Debug Key (J) Pressed.
17:56:28	OnDeinitializeMelon	Called.
17:56:28	ToggleQoLSettings	QoLmod Found, sPGAI: True, sPAPG: True.
17:56:28	OnDeinitializeMelon	QoLmod Found, showPopupforGroupAddedInventory: True.
17:56:28	OnDeinitializeMelon	QoLmod Found, showPopupforAllPartsinGroup: True.

**Comment by mannly01** [comment]
I haven't forgotten about this. I am trying to recreate or at least research the reason for this. It seems to be exactly what you assumed in your message. The mod is not seeing your key presses for K or L keys which are set in the config. The J key is hard-coded and that is why it is being seen. This makes zero sense to me.

**Comment by GermanioBR** [comment]
George,
Have you tried to talk to Meltzi or TK about this?
I think they could help you to understand why the game stopped to catch the
key pressings...
Your mod is one of the handiest when it comes to lessening the workload in
the game and I really like to see your success in making this work!

PS: You can reach then in the official discord channel for CMS

Thanks again.

GermanioBR

Em seg., 6 de mai. de 2024 às 12:42, George Mann ***@***.***>
escreveu:

**Comment by mannly01** [comment]
Thanks for the praise! I made this mod for myself because I have the same frustrations but it's nice to hear other people like it too.

I used Meitzi's code to learn how to start modding CMS and I asked a couple questions when I wrote version 1.0.0. They are capturing keypresses the exact same way that I am, so I doubt they will have insight.

Try using this file and if it still doesn't work, I will contact everyone I can for help!
[TransferAll.zip](https://github.com/mannly01/TransferAll/files/15243769/TransferAll.zip)

If it does work, let me know and I will send you a release version that cuts down on the logging. Let me know if you don't want to use K and L and I will have to hard-code the keys you do want. This can be a stopgap until I can find the problem.

Also, do the - and = keys work? They should adjust the part condition percentage and show you a popup with the current value after you press them.

Thanks for all your feedback and time helping me troubleshoot!
George

**Comment by GermanioBR** [comment]
Hi!

I'll try at night and I'll let you know how it goes, ok?

By the way, you're codding in unity or using another language?


Em qua., 8 de mai. de 2024 às 01:21, George Mann ***@***.***>
escreveu:

**Comment by mannly01** [comment]
I'm using C# which is what MelonLoader and parts of Unity are written in, but I'm not using Unity.

**Comment by GermanioBR** [comment]
Sorry for not reply sooner,  but the log file is the same as the last one...

Well,  I hope you can find whats the issue and solve this.

Thanks  again!

Em sex., 10 de mai. de 2024, 14:47, George Mann ***@***.***>
escreveu:

**Comment by mannly01** [comment]
Try the new release (1.4.4) when you have time. I uploaded an optional file on NexusMods that has the debugging turned on. If you can download that and send me the logs again, that would help a bunch!

**Comment by GermanioBR** [comment]
Not working yet... here's the log:

Transfer All - 1.4.4
CMS 2021 - 1.0.36
Log Created: 06-11-2024 05:40:01
05:40:01	ConfigFile.Init	Called.
05:40:01	ConfigFile.Init	TransferAllItemsAndGroups: K.
05:40:01	ConfigFile.Init	TransferEntireJunkyardOrBarn: L.
05:40:01	ConfigFile.Init	SetPartConditionLower: Minus.
05:40:01	ConfigFile.Init	SetPartConditionHigher: Equals.
05:40:01	ConfigFile.Init	MinPartCondition: 80.
05:40:01	ConfigFile.Init	MinNumOfItemsWarning: 700.
05:40:01	ConfigFile.Init	TransferByCategory: True.
05:40:01	ConfigFile.Init	TransferPartsOnlyAtBarnOrJunkyard: False.
05:40:01	ConfigFile.Init	TransferMapsOrCasesOnlyAtBarnOrJunkyard: False.
05:40:04	OnLateInitializeMelon	Called.
05:40:04	OnLateInitializeMelon	QoLmod Found, showPopupforGroupAddedInventory: True.
05:40:04	OnLateInitializeMelon	QoLmod Found, showPopupforAllPartsinGroup: True.
05:43:16	OnSceneWasInitialized	SceneName: garage.
06:12:53	OnSceneWasInitialized	SceneName: Junkyard.
06:20:34	OnSceneWasUnloaded	Leaving Junkyard.
06:20:34	OnSceneWasUnloaded	SceneName: Junkyard.
06:21:05	OnSceneWasInitialized	SceneName: garage.
06:39:16	OnDeinitializeMelon	Called.
06:39:16	ToggleQoLSettings	QoLmod Found, sPGAI: True, sPAPG: True.
06:39:16	OnDeinitializeMelon	QoLmod Found, showPopupforGroupAddedInventory: True.
06:39:16	OnDeinitializeMelon	QoLmod Found, showPopupforAllPartsinGroup: True.

**Comment by mannly01** [comment]
I've _finally_ had some time to look at this again. I've created a test mod to find out what key my mod thinks you are pressing. Please download and install [KeyboardTest.zip](https://github.com/user-attachments/files/16072944/KeyboardTest.zip), then (temporarily) remove all other mods.

**To use:**
(I have included a `KeyboardTest.cfg`, but the keys are the same as this mod (K & L))

1. Press the "J" key to log a test is starting.
2. Press the "K" key to log that key press.
3. Press the "J" key to log a test complete.
4. Press the "J" key to log a test is starting.
5. Press the "L" key to log that key press.
6. Press the "J" key to log test complete.

You should be able to press any other keys on your keyboard and they will be logged also. The log may get long, which is why I am using the "J" key in between the tests. We know the hard coded "J" key worked from our previous tests.

Thank you again for your help and patience while I figure this out!!
-George

**Comment by mannly01** [comment]
I'd still like you to try the above test, but here is the debug update that _hopefully_ fixes your problem.
[TransferAll (debug).zip](https://github.com/user-attachments/files/16088579/TransferAll.debug.zip)

**Comment by MeitziQ** [comment]
One possible cause is player with QoLmod AND player is using garage extension map OR using free drive debug feature. In that case mod might confuse for non-standard scenename.

**Comment by GermanioBR** [comment]
> One possible cause is player with QoLmod AND player is using garage extension map OR using free drive debug feature. In that case mod might confuse for non-standard scenename.

This is my case. I have QoL and Expansion Garage too...

I´ll test this new version tonight ok? Thanks!

**Comment by mannly01** [comment]
Use the same instructions from my KeyboardTest with this new debug version. I have added a SceneName logger when you press the "J" key. Thanks again!!

**Comment by mannly01** [comment]
Latest version 1.4.6 _should_ fix everything! You shouldn't need the DEBUG version if you don't want it.

**Comment by mannly01** [comment]
Bug fixed with release version 1.4.6.
